"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, Clock3, RefreshCw } from "lucide-react";
import { Badge } from "@/ui/common/badge";
import { Button } from "@/ui/common/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/ui/common/card";

type Task = { id: number; taskCode: string; status: string; progress: number; updatedAt: string; asset: { assetCode: string; title: string; sourceType: string } };
type Data = { stats: { totalAssets: number; pending: number; researching: number; completed: number; failed: number; todayCompleted: number; current: Task | null; latestCompleted: Task | null }; items: Task[] };
const labels: Record<string, string> = { RESEARCHING: "研究中", FACT_CHECKING: "事实验证中", BUSINESS_ANALYZING: "商业分析中", CONTENT_DECISION: "内容去向判断", COMPLETED: "已完成" };

export default function ResearchDashboardClient() {
  const [data, setData] = useState<Data | null>(null);
  const load = useCallback(async () => { const response = await fetch("/api/admin/research?pageSize=20&sort=updated", { cache: "no-store" }); const result = await response.json(); if (result.success) setData(result.data); }, []);
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 15000); return () => window.clearInterval(timer); }, [load]);
  const stats = data?.stats;
  const percent = stats && stats.totalAssets ? Math.round((stats.completed / stats.totalAssets) * 100) : 0;
  return <main className="mx-auto max-w-6xl space-y-5 p-4 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><Link href="/admin/research" className="inline-flex items-center text-sm text-muted-foreground hover:text-primary"><ArrowLeft className="mr-1 h-4 w-4" />返回 AI研究中心</Link><h1 className="mt-2 text-2xl font-bold">研究进度仪表盘</h1><p className="mt-1 text-sm text-muted-foreground">自动刷新间隔 15 秒；进度来自任务状态和研究结果导入。</p></div><Button variant="outline" onClick={() => void load()}><RefreshCw className="mr-2 h-4 w-4" />刷新</Button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card><CardContent className="p-5"><div className="text-sm text-muted-foreground">整体进度</div><div className="mt-2 text-4xl font-bold text-primary">{percent}%</div><div className="mt-3 h-3 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary transition-all" style={{ width: `${percent}%` }} /></div><div className="mt-2 text-xs text-muted-foreground">已完成 {stats?.completed ?? "—"}/{stats?.totalAssets ?? "—"}</div></CardContent></Card><Metric title="待研究" value={stats?.pending} icon={<Clock3 className="h-5 w-5" />} /><Metric title="当前处理中" value={stats?.researching} icon={<RefreshCw className="h-5 w-5" />} /><Metric title="今日完成" value={stats?.todayCompleted} icon={<CheckCircle2 className="h-5 w-5" />} /></div><div className="grid gap-4 lg:grid-cols-2"><FocusCard title="当前处理中" task={stats?.current} empty="当前没有正在处理的任务" /><FocusCard title="最近完成" task={stats?.latestCompleted} empty="还没有完成任务" /></div><Card><CardHeader><CardTitle>最近更新任务</CardTitle></CardHeader><CardContent>{!data ? <div className="py-10 text-center text-muted-foreground">加载中…</div> : <div className="space-y-2">{data.items.map((task) => <Link key={task.id} href={`/admin/research/tasks/${task.id}`} className="flex flex-wrap items-center gap-3 rounded-lg border p-3 hover:bg-muted/30"><span className="font-mono text-sm text-primary">{task.taskCode}</span><span className="min-w-0 flex-1 truncate">{task.asset.assetCode} · {task.asset.title}</span><Badge variant={task.status === "COMPLETED" ? "default" : "secondary"}>{labels[task.status] || task.status}</Badge><span className="text-sm">{task.progress}%</span></Link>)}</div>}</CardContent></Card></main>;
}

function Metric({ title, value, icon }: { title: string; value?: number; icon: React.ReactNode }) { return <Card><CardContent className="flex items-center gap-3 p-5"><div className="rounded-lg bg-primary/10 p-2 text-primary">{icon}</div><div><div className="text-sm text-muted-foreground">{title}</div><div className="text-3xl font-bold">{value ?? "—"}</div></div></CardContent></Card>; }
function FocusCard({ title, task, empty }: { title: string; task?: Task | null; empty: string }) { return <Card><CardHeader><CardTitle className="text-lg">{title}</CardTitle></CardHeader><CardContent>{task ? <Link href={`/admin/research/tasks/${task.id}`} className="block rounded-xl border p-4 hover:bg-muted/30"><div className="flex items-center justify-between gap-3"><span className="font-mono text-primary">{task.taskCode}</span><Badge variant={task.status === "COMPLETED" ? "default" : "secondary"}>{labels[task.status] || task.status}</Badge></div><div className="mt-3 font-medium">{task.asset.assetCode} · {task.asset.title}</div><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{ width: `${task.progress}%` }} /></div><div className="mt-1 text-right text-xs text-muted-foreground">{task.progress}%</div></Link> : <div className="py-8 text-center text-sm text-muted-foreground">{empty}</div>}</CardContent></Card>; }
